apiVersion: v1
kind: Namespace
metadata:
  name: frrtest
---
apiVersion: v1
kind: Pod
metadata:
  name: frr
  namespace: frrtest
spec:
  volumes:
    - name: frr-config
      configMap:
        name: frr-config
  containers:
    - name: frr
      securityContext:
        capabilities:
          add: ["NET_ADMIN", "NET_RAW", "SYS_ADMIN", "NET_BIND_SERVICE"]
      image: frr:dev
      env:
        - name: TINI_SUBREAPER
          value: "true"
      volumeMounts:
        - name: frr-config
          mountPath: /etc/frr
      # The command is FRR's default entrypoint & waiting for the log file to appear and tailing it.
      # If the log file isn't created in 60 seconds the tail fails and the container is restarted.
      # This workaround is needed to have the frr logs as part of kubectl logs -c frr < speaker_pod_name >.
      command:
        - /bin/sh
        - -c
        - |
          /sbin/tini -- /usr/lib/frr/docker-start &
          attempts=0
          until [[ -f /tmp/frr.log || $attempts -eq 60 ]]; do
            sleep 1
            attempts=$(( $attempts + 1 ))
          done
          tail -f /tmp/frr.log
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frr-config
  namespace: frrtest
data:
  daemons: |
    zebra=yes
    bgpd=yes
    ospfd=yes
    ospf6d=no
    ripd=no
    ripngd=no
    isisd=no
    pimd=no
    ldpd=yes
    nhrpd=no
    eigrpd=no
    babeld=no
    sharpd=no
    staticd=yes
    pbrd=no
    bfdd=yes
    fabricd=no

    vtysh_enable=yes
    zebra_options=" -s 90000000 --daemon -A 127.0.0.1"
    bgpd_options="   --daemon -A 127.0.0.1"
    ospfd_options="  --daemon -A 127.0.0.1"
    ospf6d_options=" --daemon -A ::1"
    ripd_options="   --daemon -A 127.0.0.1"
    ripngd_options=" --daemon -A ::1"
    isisd_options="  --daemon -A 127.0.0.1"
    pimd_options="  --daemon -A 127.0.0.1"
    ldpd_options="  --daemon -A 127.0.0.1"
    nhrpd_options="  --daemon -A 127.0.0.1"
    eigrpd_options="  --daemon -A 127.0.0.1"
    babeld_options="  --daemon -A 127.0.0.1"
    sharpd_options="  --daemon -A 127.0.0.1"
    staticd_options="  --daemon -A 127.0.0.1"
    pbrd_options="  --daemon -A 127.0.0.1"
    bfdd_options="  --daemon -A 127.0.0.1"
    fabricd_options="  --daemon -A 127.0.0.1"
  frr.conf: |
    log file /tmp/frr.log

    debug zebra events
    debug zebra vxlan
    debug bgp zebra
    debug zebra events
    debug zebra nht
    debug zebra kernel
    debug zebra rib
    debug zebra nexthop
    debug bgp neighbor-events
    debug bgp updates
    debug bgp keepalives
    debug bgp nht
    debug bgp zebra
    debug bfd network
    debug bfd peer
    debug bfd zebra

    vrf red
     vni 100
    exit-vrf

    route-map allowall permit 1

    router bgp 64514
     no bgp ebgp-requires-policy
     no bgp network import-check
     no bgp default ipv4-unicast

     neighbor 192.168.11.2 remote-as 64513
     neighbor 192.168.11.2 allowas-in origin
     !
     address-family ipv4 unicast
      neighbor 192.168.11.2 activate
      network 100.65.0.2/32
     exit-address-family

     address-family l2vpn evpn
      neighbor 192.168.11.2 activate
      neighbor 192.168.11.2 allowas-in origin
      advertise-all-vni
      advertise-svi-ip
     exit-address-family

    router bgp 64512 vrf red
     no bgp ebgp-requires-policy
     no bgp network import-check
     no bgp default ipv4-unicast

     neighbor 192.169.10.0 remote-as 64515
     !
     address-family ipv4 unicast
      neighbor 192.169.10.0 activate
      neighbor 192.169.10.0 activate
      neighbor 192.169.10.0 route-map allowall in
      neighbor 192.169.10.0 route-map allowall out
     exit-address-family
     !
     address-family l2vpn evpn
      advertise ipv4 unicast
      advertise ipv6 unicast
     exit-address-family
    exit
    !


