FROM quay.io/frrouting/frr:9.0.0

# Install keepalived and other useful networking tools
RUN apk update && \
    apk add --no-cache \
    keepalived \
    ipvsadm \
    bash \
    iproute2 \
    tcpdump \
    && rm -rf /var/cache/apk/*

# Create keepalived config directory
RUN mkdir -p /etc/keepalived

# Ensure FRR can run
RUN mkdir -p /var/log/frr && \
    chown frr:frr /var/log/frr

CMD ["/bin/bash"]
